/* Auto-generated by genmsg_cpp for file /home/gipo/groovy_workspace/sandbox/countdown/msg/CountdownResult.msg */
#ifndef COUNTDOWN_MESSAGE_COUNTDOWNRESULT_H
#define COUNTDOWN_MESSAGE_COUNTDOWNRESULT_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace countdown
{
template <class ContainerAllocator>
struct CountdownResult_ {
  typedef CountdownResult_<ContainerAllocator> Type;

  CountdownResult_()
  : executed(false)
  {
  }

  CountdownResult_(const ContainerAllocator& _alloc)
  : executed(false)
  {
  }

  typedef uint8_t _executed_type;
  uint8_t executed;


  typedef boost::shared_ptr< ::countdown::CountdownResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::countdown::CountdownResult_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct CountdownResult
typedef  ::countdown::CountdownResult_<std::allocator<void> > CountdownResult;

typedef boost::shared_ptr< ::countdown::CountdownResult> CountdownResultPtr;
typedef boost::shared_ptr< ::countdown::CountdownResult const> CountdownResultConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::countdown::CountdownResult_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::countdown::CountdownResult_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace countdown

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::countdown::CountdownResult_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::countdown::CountdownResult_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::countdown::CountdownResult_<ContainerAllocator> > {
  static const char* value() 
  {
    return "5f7651dcb2efaa4301b1ab90dbc38874";
  }

  static const char* value(const  ::countdown::CountdownResult_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x5f7651dcb2efaa43ULL;
  static const uint64_t static_value2 = 0x01b1ab90dbc38874ULL;
};

template<class ContainerAllocator>
struct DataType< ::countdown::CountdownResult_<ContainerAllocator> > {
  static const char* value() 
  {
    return "countdown/CountdownResult";
  }

  static const char* value(const  ::countdown::CountdownResult_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::countdown::CountdownResult_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# result\n\
bool executed\n\
\n\
";
  }

  static const char* value(const  ::countdown::CountdownResult_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::countdown::CountdownResult_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::countdown::CountdownResult_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.executed);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct CountdownResult_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::countdown::CountdownResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::countdown::CountdownResult_<ContainerAllocator> & v) 
  {
    s << indent << "executed: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.executed);
  }
};


} // namespace message_operations
} // namespace ros

#endif // COUNTDOWN_MESSAGE_COUNTDOWNRESULT_H

