; Auto-generated. Do not edit!


(cl:in-package countdown-msg)


;//! \htmlinclude countdownResult.msg.html

(cl:defclass <countdownResult> (roslisp-msg-protocol:ros-message)
  ((executed
    :reader executed
    :initarg :executed
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass countdownResult (<countdownResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <countdownResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'countdownResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name countdown-msg:<countdownResult> is deprecated: use countdown-msg:countdownResult instead.")))

(cl:ensure-generic-function 'executed-val :lambda-list '(m))
(cl:defmethod executed-val ((m <countdownResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader countdown-msg:executed-val is deprecated.  Use countdown-msg:executed instead.")
  (executed m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <countdownResult>) ostream)
  "Serializes a message object of type '<countdownResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'executed) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <countdownResult>) istream)
  "Deserializes a message object of type '<countdownResult>"
    (cl:setf (cl:slot-value msg 'executed) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<countdownResult>)))
  "Returns string type for a message object of type '<countdownResult>"
  "countdown/countdownResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'countdownResult)))
  "Returns string type for a message object of type 'countdownResult"
  "countdown/countdownResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<countdownResult>)))
  "Returns md5sum for a message object of type '<countdownResult>"
  "5f7651dcb2efaa4301b1ab90dbc38874")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'countdownResult)))
  "Returns md5sum for a message object of type 'countdownResult"
  "5f7651dcb2efaa4301b1ab90dbc38874")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<countdownResult>)))
  "Returns full string definition for message of type '<countdownResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# result~%bool executed~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'countdownResult)))
  "Returns full string definition for message of type 'countdownResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# result~%bool executed~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <countdownResult>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <countdownResult>))
  "Converts a ROS message object to a list"
  (cl:list 'countdownResult
    (cl:cons ':executed (executed msg))
))
