; Auto-generated. Do not edit!


(cl:in-package countdown-msg)


;//! \htmlinclude CountdownResult.msg.html

(cl:defclass <CountdownResult> (roslisp-msg-protocol:ros-message)
  ((executed
    :reader executed
    :initarg :executed
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass CountdownResult (<CountdownResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <CountdownResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'CountdownResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name countdown-msg:<CountdownResult> is deprecated: use countdown-msg:CountdownResult instead.")))

(cl:ensure-generic-function 'executed-val :lambda-list '(m))
(cl:defmethod executed-val ((m <CountdownResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader countdown-msg:executed-val is deprecated.  Use countdown-msg:executed instead.")
  (executed m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <CountdownResult>) ostream)
  "Serializes a message object of type '<CountdownResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'executed) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <CountdownResult>) istream)
  "Deserializes a message object of type '<CountdownResult>"
    (cl:setf (cl:slot-value msg 'executed) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<CountdownResult>)))
  "Returns string type for a message object of type '<CountdownResult>"
  "countdown/CountdownResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'CountdownResult)))
  "Returns string type for a message object of type 'CountdownResult"
  "countdown/CountdownResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<CountdownResult>)))
  "Returns md5sum for a message object of type '<CountdownResult>"
  "5f7651dcb2efaa4301b1ab90dbc38874")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'CountdownResult)))
  "Returns md5sum for a message object of type 'CountdownResult"
  "5f7651dcb2efaa4301b1ab90dbc38874")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<CountdownResult>)))
  "Returns full string definition for message of type '<CountdownResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# result~%bool executed~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'CountdownResult)))
  "Returns full string definition for message of type 'CountdownResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# result~%bool executed~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <CountdownResult>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <CountdownResult>))
  "Converts a ROS message object to a list"
  (cl:list 'CountdownResult
    (cl:cons ':executed (executed msg))
))
