; Auto-generated. Do not edit!


(cl:in-package countdown-msg)


;//! \htmlinclude CountdownFeedback.msg.html

(cl:defclass <CountdownFeedback> (roslisp-msg-protocol:ros-message)
  ((elapsed
    :reader elapsed
    :initarg :elapsed
    :type cl:integer
    :initform 0))
)

(cl:defclass CountdownFeedback (<CountdownFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <CountdownFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'CountdownFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name countdown-msg:<CountdownFeedback> is deprecated: use countdown-msg:CountdownFeedback instead.")))

(cl:ensure-generic-function 'elapsed-val :lambda-list '(m))
(cl:defmethod elapsed-val ((m <CountdownFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader countdown-msg:elapsed-val is deprecated.  Use countdown-msg:elapsed instead.")
  (elapsed m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <CountdownFeedback>) ostream)
  "Serializes a message object of type '<CountdownFeedback>"
  (cl:let* ((signed (cl:slot-value msg 'elapsed)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <CountdownFeedback>) istream)
  "Deserializes a message object of type '<CountdownFeedback>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'elapsed) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<CountdownFeedback>)))
  "Returns string type for a message object of type '<CountdownFeedback>"
  "countdown/CountdownFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'CountdownFeedback)))
  "Returns string type for a message object of type 'CountdownFeedback"
  "countdown/CountdownFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<CountdownFeedback>)))
  "Returns md5sum for a message object of type '<CountdownFeedback>"
  "d790168e5ba3a5b98c2f2c3464951f2f")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'CountdownFeedback)))
  "Returns md5sum for a message object of type 'CountdownFeedback"
  "d790168e5ba3a5b98c2f2c3464951f2f")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<CountdownFeedback>)))
  "Returns full string definition for message of type '<CountdownFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%int32 elapsed~%~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'CountdownFeedback)))
  "Returns full string definition for message of type 'CountdownFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%int32 elapsed~%~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <CountdownFeedback>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <CountdownFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'CountdownFeedback
    (cl:cons ':elapsed (elapsed msg))
))
