; Auto-generated. Do not edit!


(cl:in-package countdown-msg)


;//! \htmlinclude countdownFeedback.msg.html

(cl:defclass <countdownFeedback> (roslisp-msg-protocol:ros-message)
  ((elapsed
    :reader elapsed
    :initarg :elapsed
    :type cl:integer
    :initform 0))
)

(cl:defclass countdownFeedback (<countdownFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <countdownFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'countdownFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name countdown-msg:<countdownFeedback> is deprecated: use countdown-msg:countdownFeedback instead.")))

(cl:ensure-generic-function 'elapsed-val :lambda-list '(m))
(cl:defmethod elapsed-val ((m <countdownFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader countdown-msg:elapsed-val is deprecated.  Use countdown-msg:elapsed instead.")
  (elapsed m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <countdownFeedback>) ostream)
  "Serializes a message object of type '<countdownFeedback>"
  (cl:let* ((signed (cl:slot-value msg 'elapsed)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <countdownFeedback>) istream)
  "Deserializes a message object of type '<countdownFeedback>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'elapsed) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<countdownFeedback>)))
  "Returns string type for a message object of type '<countdownFeedback>"
  "countdown/countdownFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'countdownFeedback)))
  "Returns string type for a message object of type 'countdownFeedback"
  "countdown/countdownFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<countdownFeedback>)))
  "Returns md5sum for a message object of type '<countdownFeedback>"
  "d790168e5ba3a5b98c2f2c3464951f2f")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'countdownFeedback)))
  "Returns md5sum for a message object of type 'countdownFeedback"
  "d790168e5ba3a5b98c2f2c3464951f2f")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<countdownFeedback>)))
  "Returns full string definition for message of type '<countdownFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%int32 elapsed~%~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'countdownFeedback)))
  "Returns full string definition for message of type 'countdownFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%int32 elapsed~%~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <countdownFeedback>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <countdownFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'countdownFeedback
    (cl:cons ':elapsed (elapsed msg))
))
